### PR TITLE
Bump aes-gcm requirements

### PR DESCRIPTION
**Pull request by bburnichon**
Closes #31 #30 #29 #28 

Ping @ardiesaeidi @cortesoft @blovett as current people in `Edgeio` organisation

### CODE REVIEW

**Comment by bburnichon** [comment]
Ping @airencracken as found owner on crates.io

**Comment by airencracken** [comment]
Looks like I don't have the access to approve currently, I'll attempt to get that figured out today.

**Review by airencracken — APPROVED** [review]
lgtm

**Comment by bburnichon** [comment]
> Looks like I don't have the access to approve currently, I'll attempt to get that figured out today.

Did you found a way to gain write access to the repository yet?

**Pull request merged**
